[package]
name = "adventofcode2024_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
itertools = "0.13.0"
nom = "8.0.0"
regex = "1.11.1"
